"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.useTitle = exports.useKeyPress = exports.useHover = exports.useFullscreen = exports.useFavicon = exports.useEventListener = exports.useDrop = exports.useDrag = exports.useClickAway = exports.useUpdateEffect = exports.useUnmount = exports.useToggle = exports.useTimeout = exports.useSessionStorage = exports.useLocalStorage = exports.useStateWithHistoryTravel = exports.useStateWithHistory = exports.usePrevious = exports.usePersistFn = exports.useMount = exports.useInterval = exports.useFetch = exports.useDebounceFn = exports.useDebounceEffect = exports.useDebounce = exports.useCreation = exports.useCounter = exports.useCountdown = exports.useBoolean = exports.useAsync = exports.useArray = void 0;
var useArray_1 = __importDefault(require("./hooks/foundation/useArray"));
exports.useArray = useArray_1.default;
var useAsync_1 = __importDefault(require("./hooks/foundation/useAsync"));
exports.useAsync = useAsync_1.default;
var useBoolean_1 = __importDefault(require("./hooks/foundation/useBoolean"));
exports.useBoolean = useBoolean_1.default;
var useCountdown_1 = __importDefault(require("./hooks/foundation/useCountdown"));
exports.useCountdown = useCountdown_1.default;
var useCounter_1 = __importDefault(require("./hooks/foundation/useCounter"));
exports.useCounter = useCounter_1.default;
var useCreation_1 = __importDefault(require("./hooks/foundation/useCreation"));
exports.useCreation = useCreation_1.default;
var useDebounce_1 = __importDefault(require("./hooks/foundation/useDebounce"));
exports.useDebounce = useDebounce_1.default;
var useDebounceEffect_1 = __importDefault(require("./hooks/foundation/useDebounceEffect"));
exports.useDebounceEffect = useDebounceEffect_1.default;
var useDebounceFn_1 = __importDefault(require("./hooks/foundation/useDebounceFn"));
exports.useDebounceFn = useDebounceFn_1.default;
var useFetch_1 = __importDefault(require("./hooks/foundation/useFetch"));
exports.useFetch = useFetch_1.default;
var useInterval_1 = __importDefault(require("./hooks/foundation/useInterval"));
exports.useInterval = useInterval_1.default;
var useMount_1 = __importDefault(require("./hooks/foundation/useMount"));
exports.useMount = useMount_1.default;
var usePersistFn_1 = __importDefault(require("./hooks/foundation/usePersistFn"));
exports.usePersistFn = usePersistFn_1.default;
var usePrevious_1 = __importDefault(require("./hooks/foundation/usePrevious"));
exports.usePrevious = usePrevious_1.default;
var useStateWithHistory_1 = __importDefault(require("./hooks/foundation/useStateWithHistory"));
exports.useStateWithHistory = useStateWithHistory_1.default;
var useStateWithHistoryTravel_1 = __importDefault(require("./hooks/foundation/useStateWithHistoryTravel"));
exports.useStateWithHistoryTravel = useStateWithHistoryTravel_1.default;
var useStorage_1 = require("./hooks/foundation/useStorage");
Object.defineProperty(exports, "useLocalStorage", { enumerable: true, get: function () { return useStorage_1.useLocalStorage; } });
Object.defineProperty(exports, "useSessionStorage", { enumerable: true, get: function () { return useStorage_1.useSessionStorage; } });
var useTimeout_1 = __importDefault(require("./hooks/foundation/useTimeout"));
exports.useTimeout = useTimeout_1.default;
var useToggle_1 = __importDefault(require("./hooks/foundation/useToggle"));
exports.useToggle = useToggle_1.default;
var useUnmount_1 = __importDefault(require("./hooks/foundation/useUnmount"));
exports.useUnmount = useUnmount_1.default;
var useUpdateEffect_1 = __importDefault(require("./hooks/foundation/useUpdateEffect"));
exports.useUpdateEffect = useUpdateEffect_1.default;
var useClickAway_1 = __importDefault(require("./hooks/ui/useClickAway"));
exports.useClickAway = useClickAway_1.default;
var useDrag_1 = __importDefault(require("./hooks/ui/useDrag"));
exports.useDrag = useDrag_1.default;
var useDrop_1 = __importDefault(require("./hooks/ui/useDrop"));
exports.useDrop = useDrop_1.default;
var useEventListener_1 = __importDefault(require("./hooks/ui/useEventListener"));
exports.useEventListener = useEventListener_1.default;
var useFavicon_1 = __importDefault(require("./hooks/ui/useFavicon"));
exports.useFavicon = useFavicon_1.default;
var useFullscreen_1 = __importDefault(require("./hooks/ui/useFullscreen"));
exports.useFullscreen = useFullscreen_1.default;
var useHover_1 = __importDefault(require("./hooks/ui/useHover"));
exports.useHover = useHover_1.default;
var useKeyPress_1 = __importDefault(require("./hooks/ui/useKeyPress"));
exports.useKeyPress = useKeyPress_1.default;
var useTitle_1 = __importDefault(require("./hooks/ui/useTitle"));
exports.useTitle = useTitle_1.default;
